version: "3.4"

services:
  mongo-container:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "mongodb_data_container:/data/db"
    networks:
      - fiap-network
  
  apitechchallenge01:
    image: parraclaudio10/fiap-tech01
    ports:
      - "80:80"
    networks:
      - fiap-network
    depends_on:
      - "mongo-container"

volumes:
  mongodb_data_container:
    driver: local
   
networks:
  fiap-network:
    driver: bridge